using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ERPSystem.Application.DTOs.Core;
using ERPSystem.Application.Interfaces;
using ERPSystem.Domain.Entities.Core;
using ERPSystem.Infrastructure.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace ERPSystem.Infrastructure.Identity
{
    public class AuthService : IAuthService
    {
        private readonly AppDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole<Guid>> _roleManager;
        private readonly IJwtTokenService _jwtTokenService;

        private const string OwnerRoleName = "CompanyOwner";

        public AuthService(
            AppDbContext db,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole<Guid>> roleManager,
            IJwtTokenService jwtTokenService)
        {
            _db = db;
            _userManager = userManager;
            _roleManager = roleManager;
            _jwtTokenService = jwtTokenService;
        }

        public async Task<AuthResponse> RegisterOwnerAsync(RegisterOwnerRequest request, CancellationToken ct = default)
        {
            var email = request.Email.Trim().ToLowerInvariant();

            // 1) Ensure email is unique
            var existingUser = await _userManager.FindByEmailAsync(email);
            if (existingUser != null)
                throw new InvalidOperationException("Email already exists.");

            await using var tx = await _db.Database.BeginTransactionAsync(ct);

            // 2) Create Company (Id is int, generated by EF)
            var company = new Company
            {
                Name = request.Company.Name.Trim(),
                Address = request.Company.Address?.Trim(),
                IsActive = true,
                CreatedAt = DateTime.UtcNow
            };

            _db.Companies.Add(company);
            await _db.SaveChangesAsync(ct);

            // 3) Create Owner User linked to the company
            var user = new ApplicationUser
            {
                Id = Guid.NewGuid(),
                Email = email,
                UserName = email,
                FullName = request.FullName.Trim(),
                CompanyId = company.Id
            };

            var createUserResult = await _userManager.CreateAsync(user, request.Password);
            if (!createUserResult.Succeeded)
                throw new InvalidOperationException(string.Join(" | ", createUserResult.Errors.Select(e => e.Description)));

            // 4) Ensure Owner role exists
            if (!await _roleManager.RoleExistsAsync(OwnerRoleName))
            {
                var createRoleResult = await _roleManager.CreateAsync(new IdentityRole<Guid>(OwnerRoleName));
                if (!createRoleResult.Succeeded)
                    throw new InvalidOperationException(string.Join(" | ", createRoleResult.Errors.Select(e => e.Description)));
            }

            // 5) Assign Owner role
            var addToRoleResult = await _userManager.AddToRoleAsync(user, OwnerRoleName);
            if (!addToRoleResult.Succeeded)
                throw new InvalidOperationException(string.Join(" | ", addToRoleResult.Errors.Select(e => e.Description)));

            await tx.CommitAsync(ct);

            // 6) Gather roles and permissions, then issue JWT
            var roles = new[] { OwnerRoleName };
            var permissions = await GetPermissionsForRolesAsync(roles);

            return _jwtTokenService.CreateToken(user.Id, user.CompanyId, user.Email!, roles, permissions);
        }

        public async Task<AuthResponse> LoginAsync(LoginRequest request, CancellationToken ct = default)
        {
            var email = request.Email.Trim().ToLowerInvariant();

            var user = await _userManager.Users.FirstOrDefaultAsync(u => u.Email == email, ct);
            if (user == null)
                throw new InvalidOperationException("Invalid email or password.");

            var passwordOk = await _userManager.CheckPasswordAsync(user, request.Password);
            if (!passwordOk)
                throw new InvalidOperationException("Invalid email or password.");

            var roles = (await _userManager.GetRolesAsync(user)).ToArray();
            var permissions = await GetPermissionsForRolesAsync(roles);

            return _jwtTokenService.CreateToken(user.Id, user.CompanyId, user.Email!, roles, permissions);
        }

        /// <summary>
        /// Resolves all unique permissions from the given roles by fetching role claims.
        /// </summary>
        private async Task<string[]> GetPermissionsForRolesAsync(IEnumerable<string> roleNames)
        {
            var permissionSet = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var roleName in roleNames)
            {
                var role = await _roleManager.FindByNameAsync(roleName);
                if (role == null)
                    continue;

                var claims = await _roleManager.GetClaimsAsync(role);
                foreach (var claim in claims)
                {
                    if (claim.Type == "permission" && !string.IsNullOrWhiteSpace(claim.Value))
                    {
                        permissionSet.Add(claim.Value);
                    }
                }
            }

            return permissionSet.OrderBy(p => p).ToArray();
        }
    }
}
